name: allergy_check
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  intl: ^0.18.0
  intl_translation: ^0.18.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21